export const LIMITS = {
  FREE_PROJECT_LIMIT: 3,
  MAX_CONVERSATION_TOKENS: 100_000,
  MAX_UPLOAD_SIZE_BYTES: 10 * 1024 * 1024, // 10 MB
  MAX_ARCHITECTURE_RESOURCES: 50,
  MAX_CONNECTIONS: 200,
  MAX_SECURITY_GROUPS: 25,

  DAILY_BEDROCK_SPEND_LIMIT_USD: 5.0,
  CIRCUIT_BREAKER_THRESHOLD_USD: 10.0,

  UPLOAD_ALLOWED_MIME_TYPES: [
    'image/png',
    'image/jpeg',
    'image/webp',
    'application/x-yaml',
    'text/yaml',
    'application/json',
    'application/pdf',
  ] as const,

  UPLOAD_PRESIGNED_URL_EXPIRY_SECONDS: 300,

  CFN_TEMPLATE_MAX_SIZE_BYTES: 460_800, // 450 KB (AWS limit is 460,800)
  CFN_STACK_NAME_MAX_LENGTH: 128,

  API_RATE_LIMIT_PER_USER_PER_SECOND: 10,
  WEBSOCKET_IDLE_TIMEOUT_SECONDS: 600,

  PRICE_CACHE_TTL_SECONDS: 86_400, // 24 hours

  ARCHITECTURE_SCHEMA_VERSION: '1.0' as const,
};

export const NAMING_PREFIX_PATTERN = /^[a-z][a-z0-9-]{2,19}$/;
